# Generated by Django 2.2.12 on 2020-04-15 10:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ds',
            name='Student_image',
            field=models.ImageField(blank=True, height_field=500, upload_to='', verbose_name='image of student', width_field=500),
        ),
        migrations.AlterField(
            model_name='ds',
            name='year_of_join',
            field=models.DateField(default=datetime.datetime(2020, 4, 15, 10, 29, 47, 660042, tzinfo=utc), verbose_name='joining year in college'),
        ),
    ]
