# Generated by Django 2.2.12 on 2020-04-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20200415_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ds',
            name='Student_image',
        ),
        migrations.RemoveField(
            model_name='ds',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ds',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='ds',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='ds',
            name='email_id_college',
        ),
        migrations.RemoveField(
            model_name='ds',
            name='initial',
        ),
        migrations.RemoveField(
            model_name='ds',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='ds',
            name='school_details',
        ),
        migrations.RemoveField(
            model_name='ds',
            name='year_of_join',
        ),
    ]
