# Generated by Django 2.2.12 on 2020-04-15 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20200415_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='ds',
            name='dept',
            field=models.CharField(choices=[('CSE', 'COMPUTER SCIENCE ENGINEERING'), ('ECE', 'ELECTRONCS AND COMMUNICATION ENGINEERING'), ('IT', 'INFORMATION TECHNOLOGY'), ('CE', 'CIVIL ENGINEERING'), ('AE', 'AERONAUTICAL ENGINEERING'), ('EEE', 'ELECTRICAL AND ELECTRONICS ENGINEERING'), ('EI', 'ELECTRICAL INSTRUMENTATION'), ('FT', 'FASHION TECHNOLOGY'), ('ISE', 'INFORMATION SCIENCE ENGINEERING'), ('TXT', 'TEXITLE ENGINEERING')], default=0, max_length=500, verbose_name='department going to choose'),
        ),
        migrations.AddField(
            model_name='ds',
            name='email_id',
            field=models.EmailField(default='@gmail.com', help_text='personal mail id', max_length=254, unique=True, verbose_name='email of student personal'),
        ),
        migrations.AddField(
            model_name='ds',
            name='initial',
            field=models.CharField(default=None, max_length=10, verbose_name='initial of student'),
        ),
        migrations.AddField(
            model_name='ds',
            name='year_of_join',
            field=models.DateField(default=datetime.datetime(2020, 4, 15, 10, 48, 9, 725615, tzinfo=utc), verbose_name='joining year in college'),
        ),
    ]
