# Generated by Django 2.2.12 on 2020-04-15 10:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20200415_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ds',
            name='initial',
            field=models.CharField(default=0, max_length=10, verbose_name='initial of student'),
        ),
        migrations.AlterField(
            model_name='ds',
            name='year_of_join',
            field=models.DateField(default=datetime.datetime(2020, 4, 15, 10, 49, 2, 220358, tzinfo=utc), verbose_name='joining year in college'),
        ),
    ]
