# Generated by Django 2.2.12 on 2020-04-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20200415_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ds',
            name='year_of_join',
        ),
    ]
