# Generated by Django 2.2.12 on 2020-04-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_remove_ds_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ds',
            name='email_id_college',
            field=models.EmailField(help_text='for office purpose only', max_length=254, unique=True, verbose_name='email to be given in school'),
        ),
    ]
