# Generated by Django 2.2.12 on 2020-04-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_auto_20200415_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='ds',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ds',
            name='email_id_college',
            field=models.EmailField(help_text='for office purpose only', max_length=254, unique=True, verbose_name='email to be given in school'),
        ),
    ]
