# Generated by Django 2.2.12 on 2020-04-17 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_auto_20200417_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ds',
            name='is_staff',
        ),
    ]
