# Generated by Django 2.2.12 on 2020-04-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0013_remove_ds_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='ds',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
